### ISSUE TITLE
Update to 0.20.4

### ISSUE THREAD

**Issue by cwoolum** [paulpatarinski/Cordova-Calabash-iOS-Plugin#3]
Would you be able to update this to 0.20.4 or maybe be able to provide the steps to do this?

THanks!

**Comment by uniphonic** [comment]
Looks like there is a pull request for for updating to 0.20.4 : https://github.com/paulpatarinski/Cordova-Calabash-iOS-Plugin/pull/4

Looks like it needs to be updated again though, as the current version of Calabash server is 0.21.4 https://github.com/calabash/calabash-ios/releases

I'm trying to find a way to update it as well.

**Comment by paulpatarinski** [comment]
Just updated to 0.21.4
