### ISSUE TITLE
Do you know how to add onDeviceReady in an IONIC2 App with typescript?

### ISSUE THREAD

**Issue by FJLopezGarcia** [paulpatarinski/Cordova-Calabash-iOS-Plugin#5]
Hi, 
I am trying to test the Xamarin Test Cloud with an IONIC 2 app and when I run my test for my .app, the xamarin studio says that "the app does not seem to be properly linked with Calabash. Please verify that it includes the Calabash component." To fix that in IONIC 1 app, i added the Cordova-Calabash-iOS-Plugin and your code inside the "onDeviceReady".

Do you know how to do it in and IONIC2 that uses typescript?

Thanks a lot!!

**Comment by FJLopezGarcia** [comment]
**app.component.ts**

//Xamarin: Add the Cordova Calabash Plugin & Start the HTTP Server from app.js
    if(window['calabash']){
      var success = function() {
        console.log("Calabash Server started");
      }
      var failure = function() {
        console.log("Error starting Calabash Server");
      }
      window['calabash'].start(success, failure);
    }
    //End Xamarin

**Comment by paulpatarinski** [comment]
Looks like you figured it out. Here is another example from an ionic 2 app with Typescript

https://github.com/paulpatarinski/alternative-facts/blob/master/src/app/app.component.ts
