### ISSUE TITLE
Cordova Xamarin Cloud: Unable to contact test backend running in app.

### ISSUE THREAD

**Issue by Devapal** [paulpatarinski/Cordova-Calabash-iOS-Plugin#6]
I am trying to deploy iOS tests on to Test Cloud.
I am working on a  Cordova app (Hybrid) and I am using Xamarin UI test.
I added the Cordova-Calabash-iOS-Plugin to my Corvoda Project and
Edit www/js/index.js and add the following code inside onDeviceReady

if(window.calabash){
    var success = function() {
        console.log("Calabash Server started");
    }

    var failure = function() {
        console.log("Error starting Calabash Server");
    }

    calabash.start(success, failure);
}

After the above 2 steps, I generated and Xcode.proj and generated an .ipa file.

On the Xamarin Test Cloud the error says: SetUp : System.Exception : Unable to contact test backend running in app. A common cause is that the app is not properly linked with Calabash. Please verify that it includes the Calabash component.

Do I need to link Calabash Framework to my Xcode Proj ? Mentioned in the below link. https://developer.xamarin.com/guides/testcloud/calabash/quickstarts/xcode/linking-the-calabash-framework/

Please Advise
Thanks
Dev

**Comment by paulpatarinski** [comment]
This plugin includes the framework. Run the project in xcode...you should see a log statement that the Calabash server has been started. Also try upgrading to the latest version i published today 0.21.3.
```
cordova plugin add cordova-plugin-calabash-ios
```
